### ISSUE TITLE
Adding black + isort

### ISSUE THREAD

**Issue by mateuszklimek** [redata-team/redata#21]
It will be really good to automatically format code which is commited

**Comment by dlbas** [comment]
@mateuszklimek I can work on that

**Comment by mateuszklimek** [comment]
@dlbas Sound great! I think for start I would just enable it to run and we can gradually transition to having all files 'blacked' when new things are added. Sounds good for you?

Also from my experience in the past, I used it together with running automatically via git hooks, so something to consider also doing but not 100% if needed now.
