### ISSUE TITLE
How about you don't spam people?

### ISSUE THREAD

**Issue by hyperized** [redata-team/redata#72]
What's up with that? 

Stop sending unsolicited email to other Github users to sell your product.

**Comment by mateuszklimek** [comment]
I got many positive replays and very few people were not happy with the message.
Lot of people thanked for sending an email to them, calling it spam is really unfair.
Especially that I'm not selling anything to you...  your email is public and profile suggests you maybe interested in the topic so assumption was it's ok to send a message.

Of course will not send you anything more (as also upfront mentioned in the e-mail)
