### ISSUE TITLE
[FEATURE] Allow SSL to be used if server requires it

### ISSUE THREAD

**Issue by Sambeth** [redata-team/redata#76]
**Tell us about the problem you're trying to solve**
When connecting to a redshift cluster using the ip address of the cluster as host in the connection string, an error stating `server certificate for <redshift-cluster-endpoint> does not match host name <cluster-ip-address>`.  

**Describe the solution you’d like**
Simply adding `connect_args={'sslmode': 'allow'}` parameter to the create_engine function in db_operations.py and data_source.py will solve the issue.

**Describe the alternative you’ve considered or used**
I have tried and tested the above solution and it works.

**Comment by mateuszklimek** [comment]
Hey @Sambeth sounds good, if you could make a PR with this change this would be great :) 

I can also check (when running my local tests..) if this doesn't cause any problems for others DBs.

**Comment by Sambeth** [comment]
> Hey @Sambeth sounds good, if you could make a PR with this change this would be great :)
> 
> I can also check (when running my local tests..) if this doesn't cause any problems for others DBs.

Sounds good to me. I have create a PR and linked it to this issue.
